language: julia
os:
  -linux
julia:
  0.4
  nightly
notifications:
  email: false
sudo: false
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Click")'
  - if [ -f test/runtests.jl ]; then julia --check-bounds=yes -e 'Pkg.test("Click", coverage=true)'; fi
